# Generated by Django 5.0.6 on 2024-06-28 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
