# Generated by Django 5.0.6 on 2024-06-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shippingaddress_state_alter_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
