# Generated by Django 5.0.6 on 2024-08-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Hotline',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
