# Generated by Django 5.0.6 on 2024-08-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_product_hotline_alter_product_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
    ]
