# Generated by Django 5.0.6 on 2024-08-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
