# Generated by Django 5.1 on 2024-09-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='posts',
        ),
    ]
